# Generated by Django 6.0 on 2025-12-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serializemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('configuration_id', models.IntegerField()),
                ('process_step_num', models.IntegerField()),
                ('job_number', models.CharField(max_length=255)),
                ('sub_process', models.CharField(max_length=255)),
                ('run_number', models.IntegerField()),
                ('scan_number', models.IntegerField()),
                ('process_state', models.CharField(max_length=255)),
                ('start_operator', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_operator', models.CharField(max_length=255)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('rebatch_operator', models.CharField(max_length=255)),
                ('rebatch_datetime', models.DateTimeField(blank=True, null=True)),
                ('scrapped', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
