# Generated by Django 6.0 on 2025-12-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inspectionmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionmaster',
            name='run_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionmaster',
            name='scan_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
