# Generated by Django 6.0 on 2025-12-21 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_inspectionmaster_run_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoresMasterChangelog',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_id', models.CharField(max_length=255)),
                ('configuration_id', models.IntegerField()),
                ('from_process_step_num', models.IntegerField()),
                ('to_process_step_num', models.IntegerField()),
                ('job_number', models.CharField(max_length=255)),
                ('run_number', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_details', models.CharField(max_length=255)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('app_version', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoresMasterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('configuration_id', models.IntegerField()),
                ('program_number', models.IntegerField()),
                ('die_revision', models.CharField(max_length=255)),
                ('process_step_num', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('sub_location', models.CharField(max_length=255, null=True)),
                ('slurry_batch', models.CharField(max_length=255, null=True)),
                ('job_number', models.CharField(max_length=255)),
                ('scrap_time', models.DateTimeField(max_length=255, null=True)),
                ('scrap_step', models.CharField(max_length=255, null=True)),
                ('scrap_code', models.CharField(max_length=255, null=True)),
                ('scrap_operator', models.CharField(max_length=255, null=True)),
                ('scrap_notes', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inspectionmaster',
            name='part_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PatchMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step_num', models.IntegerField()),
                ('sub_process', models.CharField(max_length=255, null=True)),
                ('run_number', models.IntegerField(blank=True, null=True)),
                ('patch_cycle', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('sub_location', models.CharField(max_length=255, null=True)),
                ('start_operator', models.CharField(max_length=255, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_operator', models.CharField(max_length=255, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('scrapped', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('master_fk', models.ForeignKey(db_column='part_id', on_delete=django.db.models.deletion.CASCADE, related_name='patch', to='core.coresmasterdetails')),
            ],
        ),
    ]
